---

- name: Configure zabbix userparameters
  include_role:
    name: zabbix-agent
    tasks_from: types/user_parameter
  vars:
    zabbix_agent__userparameter:
      name: ntp
      comment:
      userparameters:
        - key: ntp.drift
          command: >
            /usr/bin/env cat '{{ ntp__drift_file }}' 2>&1 | awk '{ if (match($1, /^[0-9.-]+$/)) { print $1 } else { print "ZBX_NOTSUPPORTED" > "/dev/stderr" } }'
          sudo: true
          sudo_user: '{{ ntp__service_user }}'
          sudo_command: '/usr/bin/env cat {{ ntp__drift_file }}'
          comment: get the current ntp drift
        - key: ntp.synchronisation
          command: /bin/bash -c 'ntpstat 1>/dev/null 2>&1; echo -n $((! $?))'
          comment: return 1 if server is synchronised 0 otherwise
      state: present
  tags: ['ntp', 'ntp-monitoring']
