---
language: python
cache: pip
# Tell Travis to start Docker when it brings up an environment.
services:
  - docker
env:
  - ANSIBLE='ansible~=2.7.0'
  - ANSIBLE='ansible~=2.8.0'
  - ANSIBLE='ansible~=2.9.0'
matrix:
  fast_finish: true

install:
  - >
    pip install
    ${ANSIBLE}
    'ansible-lint>=3.4.15'
    ${MOLECULE:-molecule>=2.15.0,<3.0.0}
    docker
    'testinfra>=1.7.0'

script:
  - travis_wait 30 molecule test --all

notifications:
  webhooks:
    urls: ['https://galaxy.ansible.com/api/v1/notifications/']
    if: 'branch = master OR tag IS present'
    on_failure: never
