---

- name: "Create the '{{ ntp__service_group }}' group"
  group:
    name: '{{ ntp__service_group }}'
    system: true
    state: present

- name: "Create the '{{ ntp__service_user }}' user"
  user:
    name: '{{ ntp__service_user }}'
    group: '{{ ntp__service_group }}'
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: '{{ ntp__var_directory }}'
    state: present
  register: _ntp__service_user_changed
  notify: ['restart-ntp']
  ignore_errors: true

- name: Stop NTP daemon before user update
  service:
    name: '{{ ntp__service_name }}'
    state: stopped
  when: _ntp__service_user_changed is failed

- name: "Create the '{{ ntp__service_user }}' user is present (second try)"
  user:
    name: '{{ ntp__service_user }}'
    group: '{{ ntp__service_group }}'
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: '{{ ntp__var_directory }}'
    state: present
  when: _ntp__service_user_changed is failed
  notify: ['restart-ntp']

- name: Ensure required directories exists
  file:
    path: '{{ item }}'
    owner: '{{ ntp__service_user }}'
    group: '{{ ntp__service_group }}'
    mode: 0750
    state: directory
  with_items:
    - '{{ ntp__var_directory }}'
    - '{{ ntp__log_directory }}'
    - '{{ ntp__private_crypt_dir }}'
    - '{{ ntp__statistics_dir if ntp__statistics_dir is defined else omit }}'

- name: Remove previous statistic directory directory
  file:
    path: '{{ ntp__var_directory }}/{{ ntp__statistics_dir|basename }}'
    state: absent
  when: ntp__var_directory != ntp__log_directory

- name: Ensure configuration directory exists
  file:
    path: '{{ ntp__configuration_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Remove useless service environment file
  file:
    path: '{{ ntp__service_environment }}'
    state: absent
  when: ntp__service_environment is defined

- name: 'Setup {{ ntp__configuration_file_path }}'
  template:
    src: ntp.conf.j2
    dest: '{{ ntp__configuration_file_path }}'
    owner: '{{ ntp__service_user }}'
    group: '{{ ntp__service_group }}'
    mode: 0644
  notify: ['restart-ntp']

- name: Setup keys file
  template:
    src: keys.j2
    dest: '{{ ntp__keys_file }}'
    owner: '{{ ntp__service_user }}'
    group: root
    mode: 0600
  notify: ['restart-ntp']

- name: Setup keys password file
  template:
    src: keys_passwords.j2
    dest: '{{ ntp__keys_password_file }}'
    owner: '{{ ntp__service_user }}'
    group: root
    mode: 0600
  notify: ['restart-ntp']
