---

- name: Ensure required directories exists
  file:
    path: '{{ item }}'
    owner: '{{ ntp__service_user }}'
    group: '{{ ntp__service_group }}'
    mode: 0750
    state: directory
  with_items:
    - '{{ ntp__var_directory }}'
    - '{{ ntp__log_directory }}'
    - '{{ ntp__private_crypt_dir }}'
    - '{{ ntp__statistics_dir if ntp__statistics_dir is defined else omit }}'

- name: Remove previous statistic directory directory
  file:
    path: '{{ ntp__var_directory }}/{{ ntp__statistics_dir|basename }}'
    state: absent
  when: ntp__var_directory != ntp__log_directory

- name: Ensure configuration directory exists
  file:
    path: '{{ ntp__configuration_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Get information about NTP user
  getent:
    database: passwd
    key: '{{ ntp__service_user }}'
    split: ':'
  failed_when: false

- name: "Ensure NTP user '{{ ntp__service_user }}' is present"
  user:
    name: '{{ ntp__service_user }}'
    group: '{{ ntp__service_group }}'
    shell: /bin/false
    home: '{{ ntp__var_directory }}'
    createhome: false
    system: true
    state: present
  when: ntp__service_user not in getent_passwd|d([])
  notify: ['restart-ntp' ]

- name: Install service environment file
  template:
    src: ntp.environment.j2
    dest: '{{ ntp__service_environment }}'
    owner: root
    group: root
    mode: 0644
  when: ntp__service_environment is defined
  notify: ['restart-ntp']

- name: 'Setup {{ ntp__configuration_file_path }}'
  template:
    src: ntp.conf.j2
    dest: '{{ ntp__configuration_file_path }}'
    owner: root
    group: root
    mode: 0644
  notify: ['restart-ntp']

- name: Setup keys file
  template:
    src: keys.j2
    dest: '{{ ntp__keys_file }}'
    owner: '{{ ntp__service_user }}'
    group: root
    mode: 0600
  notify: ['restart-ntp']

- name: Setup keys password file
  template:
    src: keys_passwords.j2
    dest: '{{ ntp__keys_password_file }}'
    owner: '{{ ntp__service_user }}'
    group: root
    mode: 0600
  notify: ['restart-ntp']
