---

- name: Remove the conflicting packages
  package:
    name: '{{ item }}'
    state: absent
  with_items: '{{ ntp__conflict_packages }}'

- name: Install NTP packages
  package: 
    name: '{{ item }}'
    state: present
  with_items:
    - tzdata
    - ntp
