---
# tasks file for ntp

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Check role availability
  fail:
    msg: 'This module only works with Systemd'
  when: ansible_service_mgr != 'systemd'
  tags: ['always']

- name: Importing initialization tasks
  import_tasks: init.yml
  tags: ['always']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['ntp', 'ntp-install']

- name: Importing configuration tasks
  import_tasks: configure.yml
  tags: ['ntp', 'ntp-configure']

- name: Importing service tasks
  import_tasks: service.yml
  tags: ['ntp', 'ntp-service']

- name: Optionally including monitoring tasks
  include_tasks: 'monitoring/{{ monitoring_backend }}.yml'
  loop: '{{ [ntp__monitoring]|flatten|unique|list }}'
  when: ntp__monitoring is defined
  loop_control:
    loop_var: monitoring_backend
  tags: ['ntp', 'ntp-monitoring']

- name: Optionally including facts tasks
  include_tasks: facts.yml
  when: ntp__facts|bool
  tags: ['ntp', 'ntp-facts']
