---
- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags: ['ntp']

- name: Install required packages
  package: name='{{ item }}' state=latest
  with_items: [ 'tzdata' ]
  tags: ['ntp']

- name: Include the daemon engine tasks
  include: '{{ ntp__daemon }}.yml'
  when: ntp__daemon_enabled|bool
  tags: ['ntp']
