---
- name: Remove the conflicting packages
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    '{{ ntp__conflict_packages }}'
  tags: ['ntp', 'ntpd']

- name: Install the latest version of NTP server
  package: 
    name: ntp
    state: latest
  tags: ['ntp', 'ntpd']

- name: Setup /etc/ntp.conf
  template:
    src:    'etc/ntp.conf.j2'
    dest:   '/etc/ntp.conf'
    owner:  'root'
    group:  'root'
    mode:   '0644'
    backup: yes
  notify: [ 'Restart NTP daemon' ]
  tags: ['ntp', 'ntpd']

- name: Enable NTP daemon at boot
  service:
    name: '{{ ntp__service_name }}'
    enabled: yes
  tags: ['ntp', 'ntpd']
