---

- name: Install systemd options override file
  file:
    path: '{{ ntp__systemd_override_options_dir }}/override.conf'
    state: absent
  when: ansible_service_mgr == 'systemd'
  register: _ntp__service_override
  notify: ['restart-ntp']

- name: Ensure systemd override directory state
  file:
    path: '{{ ntp__systemd_override_options_dir }}'
    state: absent
  when: ansible_service_mgr == 'systemd'
  register: _ntp__service_dir
  notify: ['restart-ntp']

- name: 'Install {{ prometheus_exporter__name }} systemd service unit file'
  template:
    src: ntp.systemd.j2
    dest: '/etc/systemd/system/{{ ntp__service_name }}.service'
    owner: root
    group: root
    mode: 0640
  when: ansible_service_mgr == 'systemd'
  register: _ntp__service_systemd
  notify: ['restart-ntp']

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'
    and (
      _ntp__service_dir is changed
      or _ntp__service_override is changed
      or _ntp__service_systemd is changed
    )

- meta: flush_handlers

- name: Ensure NTP daemon is started and enabled on boot
  service:
    name: '{{ ntp__service_name }}'
    enabled: '{{ ntp__service_enabled|bool }}'
    state: "{{ ntp__service_enabled|bool|ternary('started', 'stopped') }}"
