---

- name: Ensure NTP daemon is started and enabled on boot
  service:
    name:    '{{ ntp__service_name }}'
    enabled: '{{ ntp__service_enabled|bool }}'
    state:   "{{ ntp__service_enabled|bool|ternary('started', 'stopped') }}"
