---

- name: Ensure systemd override directory state
  file:
    path: '{{ ntp__systemd_override_options_dir }}'
    state: "{{ ntp__systemd_override_options_enabled|bool|ternary('directory', 'absent') }}"
  when: ansible_service_mgr == 'systemd'
  register: _ntp__service_dir
  notify: ['restart-ntp']

- name: Install systemd options override file
  template:
    src: override.systemd.d.j2
    dest: '{{ ntp__systemd_override_options_dir }}/override.conf'
  when: ansible_service_mgr == 'systemd' and ntp__systemd_override_options_enabled|bool
  register: _ntp__service_override
  notify: ['restart-ntp']

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd' and (
      _ntp__service_dir is changed or _ntp__service_override is changed
    )

- meta: flush_handlers

- name: Ensure NTP daemon is started and enabled on boot
  service:
    name: '{{ ntp__service_name }}'
    enabled: '{{ ntp__service_enabled|bool }}'
    state: "{{ ntp__service_enabled|bool|ternary('started', 'stopped') }}"
